### ISSUE TITLE
Button frame

### ISSUE THREAD

**Issue by xxczaki** [xxczaki/calculator.js#3]
When you click a button you will see an ugly looking frame.

**Comment by ajayns** [comment]
Hey @xxczaki  I'd like to help but I can't seem to exactly get the issue you're talking about. Can you please screenshot or show what exactly happens?

**Comment by xxczaki** [comment]
This ugly frame around the button when you click on it:
![ezgif-2-4b17899d2b](https://user-images.githubusercontent.com/22645979/29725615-0a23c6d0-89cd-11e7-9b95-034ff5377d7c.gif)

**Comment by ajayns** [comment]
Let me see if I can solve this issue. Will PR if  I have a solution @xxczaki
